apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    base:
      enabled: false
    pilot:
      enabled: true
    ingressGateways:
  values:
    global:
      caAddress: 9.46.83.230:31238
