apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    base:
      enabled: true
    pilot:
      enabled: false
    istiodRemote:
      enabled: true
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true

  addonComponents:
    prometheus:
      enabled: false
  values:
    global:
      caAddress: 9.46.83.230:31236

    istiodRemote:
            injectionURL: https://9.46.83.230:31238/inject

    base:
            validationURL: https://9.46.83.230:31238/validate
