apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      discoveryAddress: 9.46.83.230:31236
      controlPlaneAuthPolicy: MUTUAL_TLS
  components:
    base:
      enabled: true
    pilot:
      enabled: true
    ingressGateways:
  values:
    global:
      caAddress: 9.46.83.230:31236
