spec:
  type: NodePort
  ports:
    - port: 15010
      name: grpc-xds # plaintext
    - port: 15012
      name: https-dns # mTLS with k8s-signed cert
      nodePort: 31236
    - port: 15017
      name: https-webhook # validation and injection
      targetPort: 15017
      nodePort: 31238
    - port: 15014
      name: http-monitoring # prometheus stats
    - name: dns
      port: 53
      targetPort: 15053
      protocol: UDP
    - name: dns-tls
      port: 853
      targetPort: 15053
      protocol: TCP
