# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgi-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tgi-deploy
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: tgi-deploy
    spec:
      containers:
        - env:
            - name: http_proxy
              value: ${http_proxy}
            - name: https_proxy
              value: ${https_proxy}
            - name: shm-size
              value: "1g"
            - name: model-id
              value: "HuggingFaceH4/zephyr-7b-beta"
            - name: disable-custom-kernels
              value: ""
          image: ghcr.io/huggingface/text-generation-inference:1.4
          name: tgi-deploy-demo
          volumeMounts:
            - mountPath: /data
              name: model-volume
          ports:
            - containerPort: 8180
          resources:
            limits:
              cpu: 56000m
              memory: 26Gi
            requests:
              cpu: 56000m
              memory: 26Gi
      serviceAccountName: default
      volumes:
        - name: model-volume
          hostPath:
            # directory location on host
            path: /mnt/model
            # this field is optional
            type: Directory
---
kind: Service
apiVersion: v1
metadata:
  name: tgi-deploy
spec:
  type: NodePort
  selector:
    app: tgi-deploy
  ports:
    - name: service
      port: 8180
      targetPort: 80
      nodePort: 30180
