# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-deploy
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: ui-deploy
    spec:
      containers:
        - env:
            - name: BASIC_URL
              value: "http://{node_ip}:30123/v1"
            - name: SVC_PORT
              value: "5176"
          image: ${docker_registry}/gen-ai-examples/ui:v1.0
          name: ui-deploy-demo
          command: ["npm", "run", "dev", "--", "--port", "5176", "--host"]
          ports:
            - containerPort: 5176
          resources:
            limits:
              cpu: 2000m
              memory: 1Gi
            requests:
              cpu: 1000m
              memory: 1Gi
      serviceAccountName: default
---
kind: Service
apiVersion: v1
metadata:
  name: ui-deploy
spec:
  type: NodePort
  selector:
    app: ui-deploy
  ports:
    - name: service
      port: 5176
      targetPort: 5176
      nodePort: 30176
