# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: mc e2e test

on:
  pull_request:
    branches: [master]
    types: [opened, reopened, ready_for_review, synchronize] # added `ready_for_review` since draft is skipped
    paths:
      - microservices-connector/**
      - .github/workflows/mc-e2e.yaml
  workflow_dispatch:

# If there is a new commit, the previous jobs will be canceled
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GOSRC_DIR: "microservices-connector"

jobs:
  kind:
    runs-on: inspur-icx-1
    steps:
      - name: Checkout out Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run e2e test for microservices-connector
        run: |
          .github/workflows/scripts/e2e/mc_test.sh validate_chatqna
      - name: Clean up e2e test for microservices-connector
        run: |
          kubectl delete ns chatqa
          kubectl delete ns system
          kuectl delete crd gmconnectors.gmc.opea.io
