# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: mc e2d test

on:
  pull_request:
    branches: [master]
    types: [opened, reopened, ready_for_review, synchronize] # added `ready_for_review` since draft is skipped
    paths:
      - microservices-connector/**
      - .github/workflows/mc-e2e.yaml
  workflow_dispatch:

# If there is a new commit, the previous jobs will be canceled
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GOSRC_DIR: "microservices-connector"

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kind
        run: |
          export GOBIN=$(go env GOPATH)/bin
          export PATH=$PATH:$GOBIN
          mkdir -p $GOBIN

          curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
          chmod +x kubectl && mv kubectl $GOBIN
          wget https://github.com/kubernetes-sigs/kind/releases/download/v0.5.0/kind-linux-amd64 && chmod +x kind-linux-amd64 && mv kind-linux-amd64 $GOBIN/kind

          kind create cluster --wait 300s
          export KUBECONFIG="$(kind get kubeconfig-path)"
          kubectl wait --for=condition=Ready pods --all --namespace kube-system
          kubectl cluster-info
          kubectl get pods -n kube-system
      - name: Run e2e test for microservices-connector
        run: |
        .github/workflows/scripts/mc_test.sh init_codegen
      - name: Clean up e2e test for microservices-connector
        run: |
        kind delete cluster
